import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "./navbar.css"; // Importez le CSS de la barre de navigation ici

import Navigation from "./components/Navigation";
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script async src="https://www.tiktok.com/embed.js"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        <div style={{ position: 'relative', width: '100%', overflow: 'hidden' }}>
          <Image
            src="/images/banniere.png"
            alt="Bannière du club US Marquillie"
            layout="responsive"
            width={800} // Nouvelle largeur de la bannière
            height={150} // Nouvelle hauteur de la bannière
            quality={100}
            objectFit="contain"
          />
          <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', zIndex: 10, textAlign: 'center' }}>
            <Image
              src="/images/logo.jpg"
              alt="Logo du club US Marquillie"
              width={100}
              height={100}
            />
          </div>
        </div>
        <div style={{ paddingTop: '30px' }}>{children}</div> {/* Ajustement du padding-top */}
      </body>
    </html>
  );
}
